# Generated by Django 3.0.8 on 2023-11-09 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('timezone', models.TimeField()),
                ('country_code', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=10)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(default=0)),
                ('subscription_status', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('secondary_email', models.EmailField(max_length=200)),
                ('secondary_phone', models.IntegerField(default=0)),
                ('address', models.TextField()),
                ('zip_code', models.CharField(max_length=200)),
                ('income', models.EmailField(max_length=254)),
                ('registered_device_1', models.IntegerField(default=0)),
                ('registered_device_2', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='LoginsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
