# Generated by Django 3.0.8 on 2023-11-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_view_au_coffee', 'Can View AU Coffee'), ('can_view_us_coffee', 'Can View US Coffee'), ('can_view_us_little_champ', 'Can View US Little Champ'), ('can_view_au_little_champ', 'Can View AU Little Champ')), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
