# Generated by Django 3.0.8 on 2024-09-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240528_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expire_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='free_trial',
            field=models.BooleanField(default=False),
        ),
    ]
