# Generated by Django 3.0.8 on 2024-11-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240913_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='corp_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Corporation Address'),
        ),
        migrations.AddField(
            model_name='region',
            name='corp_contact',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Corporation Contact'),
        ),
        migrations.AddField(
            model_name='region',
            name='corp_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Corporation Email'),
        ),
        migrations.AddField(
            model_name='region',
            name='corp_number',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Corporation Number'),
        ),
        migrations.AddField(
            model_name='region',
            name='corp_text',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Corporation Text'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
