# Generated by Django 3.0.8 on 2025-01-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20241107_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='tradingview_exchange_code',
            field=models.CharField(default='NYSE', max_length=10, null=True, verbose_name='TradingView Code'),
        ),
    ]
