# Generated by Django 3.0.8 on 2025-02-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_region_tradingview_exchange_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='region_hostname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
