# Generated by Django 6.0 on 2025-12-27 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_region_region_hostname'),
    ]

    def set_australia_default(apps, schema_editor):
        Region = apps.get_model('users', 'Region')
        # Reset all regions
        Region.objects.all().update(is_default=False)
        # Set Australia as default
        # Assuming country_code or country_name is used to identify. 
        # Checking existing code, country_code is likely 'AU' or name 'Australia'.
        # I'll try to match by name 'Australia' as it's more explicit.
        Region.objects.filter(country_name__iexact='Australia').update(is_default=True)

    operations = [
        migrations.RunPython(set_australia_default),
    ]
