# Generated by Django 3.0.8 on 2024-06-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='feature_image_url',
            field=models.ImageField(upload_to='uploads/articles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature_image_url',
            field=models.ImageField(upload_to='uploads/products/'),
        ),
    ]
