# Generated by Django 3.0.8 on 2024-06-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20240603_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='traget_price',
        ),
    ]
