# Generated by Django 3.0.8 on 2024-06-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_auto_20240607_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_platinum',
            field=models.BooleanField(default=False),
        ),
    ]
