# Generated by Django 3.0.8 on 2024-06-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_product_is_platinum'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spec_1',
            field=models.CharField(default='Specification', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_2',
            field=models.CharField(default='Specification', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_3',
            field=models.CharField(default='Specification', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_4',
            field=models.CharField(default='Specification', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_5',
            field=models.CharField(default='Specification', max_length=255),
        ),
    ]
