# Generated by Django 3.0.8 on 2024-09-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_auto_20240627_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_free_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='setup_password',
            field=models.CharField(default='Welcome@v2u', max_length=15),
        ),
    ]
