# Generated by Django 3.0.8 on 2024-10-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240913_1837'),
        ('marketing', '0009_auto_20240913_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('handle', models.CharField(choices=[('fb', 'FACEBOOK'), ('x', 'X'), ('li', 'LINKEDIN'), ('insta', 'INSTAGRAM'), ('yt', 'YOUTUBE')], max_length=10)),
                ('handle_url', models.CharField(default='#', max_length=255)),
                ('region', models.ManyToManyField(to='users.Region')),
            ],
        ),
    ]
