# Generated by Django 3.0.8 on 2025-01-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20241107_1720'),
        ('marketing', '0010_socialhandle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='regions',
            field=models.ManyToManyField(related_name='pregions', to='users.Region'),
        ),
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pregion', to='users.Region'),
        ),
    ]
