# Generated by Django 3.0.8 on 2025-02-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_auto_20250120_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='region',
        ),
    ]
