# Generated by Django 4.2.27 on 2025-12-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_remove_product_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='user_agent',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='socialhandle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
