# Generated by Django 6.0 on 2025-12-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_alter_lead_email_alter_lead_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
