# Generated by Django 3.0.8 on 2023-11-09 06:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
        ('company', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('short_description', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('published_date', models.DateTimeField()),
                ('draft_date', models.DateTimeField(auto_now=True, verbose_name='Draft date')),
                ('traget_price', models.IntegerField()),
                ('is_free', models.BooleanField(null=True)),
                ('is_featured', models.BooleanField(null=True)),
                ('feature_image_url', models.CharField(max_length=250)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ManyToManyField(to='company.Company')),
                ('product', models.ManyToManyField(to='marketing.Product')),
                ('region', models.ManyToManyField(to='users.Region')),
                ('sector', models.ManyToManyField(to='company.Sector')),
                ('segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.ResearchTypes')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
