# Generated by Django 3.0.8 on 2024-05-28 06:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
