# Generated by Django 3.0.8 on 2024-06-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20240528_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_daily',
            field=models.BooleanField(null=True),
        ),
    ]
