# Generated by Django 3.0.8 on 2024-06-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20240603_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='traget_price',
            field=models.FloatField(),
        ),
    ]
