# Generated by Django 3.0.8 on 2024-10-21 20:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20240604_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cmp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='report',
            name='custom_templates',
            field=models.CharField(choices=[('t20231201', 'Template Dec 23'), ('t20241001', 'Template Oct 24')], default='t20241001', max_length=9),
        ),
        migrations.AddField(
            model_name='report',
            name='left_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='pdf_url',
            field=models.FileField(null=True, upload_to='uploads/reports/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='report',
            name='recommendation',
            field=models.CharField(choices=[('BU', 'Buy'), ('SB', 'Speculative Buy'), ('HD', 'Hold'), ('SL', 'Sell'), ('EP', 'Expensive'), ('WW', 'Wait & Watch'), ('UP', 'Update'), ('NA', 'None')], default='NA', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('hig', 'High'), ('NA', 'None')], default='NA', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='summary_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='feature_image_url',
            field=models.ImageField(null=True, upload_to='uploads/reports/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='traget_price',
            field=models.FloatField(default=0.0),
        ),
    ]
