# Generated by Django 3.0.8 on 2024-10-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20241022_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf_url',
            field=models.FileField(blank=True, null=True, upload_to='uploads/reports/%Y/%m/%d/'),
        ),
    ]
