# Generated by Django 3.0.8 on 2023-11-10 07:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('feature_image_url', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField()),
                ('meta_keyword', models.CharField(max_length=255)),
                ('summary', ckeditor.fields.RichTextField()),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Region')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
