# Generated by Django 3.0.8 on 2024-06-06 19:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='pages',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
