# Generated by Django 3.0.8 on 2024-06-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240606_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='feature_image_url',
            field=models.ImageField(upload_to='uploads/pages/%Y/%m/%d/'),
        ),
    ]
