# Generated by Django 3.0.8 on 2023-11-09 06:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('feature_image_url', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Region')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='ResearchTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Region')),
            ],
            options={
                'verbose_name': 'Research Type',
                'verbose_name_plural': 'Research Types',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField()),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Region')),
                ('sector', models.ManyToManyField(to='company.Sector')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
