# Generated by Django 3.0.8 on 2024-06-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='feature_image_url',
            field=models.ImageField(upload_to='uploads/sectors/'),
        ),
    ]
