# Generated by Django 3.0.8 on 2025-01-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20241107_1720'),
        ('company', '0002_auto_20240603_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='regions',
            field=models.ManyToManyField(related_name='cregions', to='users.Region'),
        ),
        migrations.AddField(
            model_name='researchtypes',
            name='regions',
            field=models.ManyToManyField(null=True, related_name='rtregions', to='users.Region'),
        ),
        migrations.AddField(
            model_name='sector',
            name='regions',
            field=models.ManyToManyField(related_name='sregions', to='users.Region'),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cregion', to='users.Region'),
        ),
        migrations.AlterField(
            model_name='researchtypes',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtregion', to='users.Region'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='feature_image_url',
            field=models.ImageField(null=True, upload_to='uploads/sectors/'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sregion', to='users.Region'),
        ),
    ]
