# Generated by Django 4.2.27 on 2025-12-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_clienttestimonials_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttestimonials',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
