# Generated by Django 3.0.8 on 2023-11-09 06:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Draft date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Draft date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Created_By', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_link', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('IN', 'Initiated'), ('PR', 'Processed'), ('RJ', 'Rejected')], default='FL', max_length=2)),
                ('payment_status', models.CharField(choices=[('IN', 'Initiated'), ('PR', 'Processed'), ('RJ', 'Rejected')], default='IN', max_length=2)),
                ('Invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('description', ckeditor.fields.RichTextField()),
                ('hot', models.BooleanField()),
                ('new', models.BooleanField()),
                ('most_sellable', models.BooleanField()),
                ('feature_image_url', models.CharField(max_length=250)),
                ('products', models.ManyToManyField(to='marketing.Product')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Package'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='users.User'),
        ),
    ]
